sonar.projectKey=yusufrezza_tugas-devops-31
sonar.organization=yusufrezza
sonar.projectName=tugas-devops-31
sonar.sourceEncoding=UTF-8

# Sumber & test
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage (dari Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# (opsional) Sesuaikan jika pakai monorepo:
# sonar.working.directory=.sonar
